#+TITLE:  yt-dlp User Manuel
#+AUTHOR: Likhon Barai
#+EMAIL:  likhonhere007@gmail.com
#+DATE:   2022 Dec 06
#+TAGS:   blog tutorial yt-dlp

* Playlist

+ See the full documentation here, [[https://www.mankier.com/1/yt-dlp][yt-dlp]].

To ignore specific videos while downloading a playlist, you can do that by passing the following flags:

#+BEGIN_EXAMPLE
  --playlist-start NUMBER      Playlist video to start at (default is 1)

  --playlist-end NUMBER        Playlist video to end at (default is last)

  --playlist-items ITEM_SPEC   Playlist video items to download. Specify indices
                               of the videos in the playlist separated by
                               commas like: "-- playlist-items 1,2,5,8"
                               if you want to download videos indexed 1, 2, 5, 8 in
                               the playlist. You can specify range:
                               "--playlist-items 1-3,7,10-13", it will download
                               the videos at index 1, 2, 3, 7, 10, 11, 12 and 13.
#+END_EXAMPLE

Comma separated =playlist_index= of the videos to download. You can specify a range using =[START]:[STOP][:STEP]=. For backward compatibility, /START-STOP/ is also supported. Use negative indices to count from the right and negative STEP to download in reverse order. \\
e.g. =-I 1:3,7,-5::2= used on a playlist of size 15 will download the videos at =index 1,2,3,7,11,13,15=.

/Download all playlists of *YouTube* channel/user keeping each playlist in separate directory:/

#+begin_example
  yt-dlp -o "%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" [URL]
#+end_example

/Download *Udemy* course keeping each chapter in separate directory under MyVideos directory in your home:/

#+begin_example
  yt-dlp -u user -p password -P "~/MyVideos" -o "%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s" [URL]
#+end_example

/Download _entire series season_ keeping each series and each season in separate directory under C:/MyVideos:/

#+begin_example
  yt-dlp -P "C:/MyVideos" -o "%(series)s/%(season_number)s - %(season)s/%(episode_number)s - %(episode)s.%(ext)s" [URL]
#+end_example

* How to download YouTube movies that require login

On YouTube, movies containing radical expressions such as violence and bloodshed can only be played by logging in to your account and verifying your age. \\
For example, if you try to play the trailer for The *Suicide Squad* Extreme *Rogues, Rally* without logging in to YouTube, you will see _Please log in to verify your age_.

- Although general download apps may not support _age-restricted_ movies, ~yt-dlp~ has a function to download age-restricted movies by pretending to be logged in by reading the cookie of the browser. To read and download cookies from your browser, use a command like the one below that includes the option =--cookies-from-browser=.

#+begin_example
  yt-dlp --cookies-from-browser [browser name] [URL]
#+end_example

* How to speed up download

Streaming services that use *HLS* , such as *Twitch*, can speed up downloads by
using the parallel download function. The command to execute parallel download
is as follows:

#+begin_example
  yt-dlp -N [number of threads] [URL]
#+end_example

 - For example, you can download the target movie in parallel with 2 threads by
   typing ~yt-dlp -N 2 https://www.twitch.tv/videos/558818717~.

   As a result of actually downloading the same movie while changing the number
   of threads and measuring the download time with a stopwatch, =number of threads 1: 2 minutes 29 seconds=, =number of threads 2: 2 minutes 13 seconds=, =number of threads 3: 2 minutes= The download time was shortened as the number of threads increased, such as =6 seconds= and =number of threads 4: 2 minutes 5 seconds=.
