#+TITLE:  My Thought's
#+AUTHOR: Likhon Barai
#+EMAIL:  likhonhere007@gmail.com
#+DATE:   2022 Dec 30
#+TAGS:    blog org


* শোষণের খাতিরেই শাসন

প্রায়ই চোখে পড়ে আশ্চর্য কীর্তির ঠিক উল্টো পিঠে কুৎসিত শোষণ।
বনের বাঘকে খাঁচায় পুরে রাখলেও নিশ্চিন্তি নেই; দরকার পড়ে নিয়ম করে বাঘকে আফিম খাওয়াবার। আফিম খেলে বাঘ ঝিমিয়ে পড়তে পারে এ-হেন দুশ্চিন্তার আর কারণ থাকবে না। বাঘের বেলায় যে-রকম ব্যবস্হা, মেহনতকারী মানুষদের বেলাতেও খানিকটা সেই ধরনেরই ব্যবস্হা গড়ে উঠলো। এই ব্যবস্হাটার নাম ধর্ম।
ভারতের প্রত্নতাত্ত্বিক রাখালদাস বন্দ্যোপাধ্যায় (১৮৮৫-১৯৩০) ১৯২১ সালে সিন্ধু প্রদেশের এক প্রকান্ড ঢিবি খুঁড়ে মোহেঞ্জোদাড়ো সভ্যতার উদ্ঘাটন করেন।
রাজ্যনীতি :
গ্রীকরাই প্রথম দেখিয়েছিলো রাজাকে বাদ দিয়েও কেমন করে রাজ্য চালানো যায়। সাধারণ লোকের মত নিয়ে দেশের কাজ চালানোকে বলে গণতন্ত্র; গ্রীসের ছোট শহরগুলোতেই ইতিহাসের প্রথম গণতন্ত্রের পরিচয় পাওয়া যায়।
প্রদীপ জ্বালতে গেলে তেল পোড়াতে হয়। ওদের বেলায় তেল ছিল ওই লক্ষ লক্ষ ক্রীতদাসের জীবন।
( সঙ্গিন – গুরুতর; বিপদজনক [ তার অবস্থা খুবই সঙ্গিন। ] )
১৭৫৭-তে পলাসীর যুদ্ধ। ১৭৭৬ থেকে শিল্প-বিপ্লবের শুরু।
জীবের মৃতদেহ ফসিলে হয়ে সম্পূর্ণ পাথরে পরিণত হয় কিভাবে?
জীবদেহ অসংখ্য কোষ দিয়ে গঠিত। জীবের মৃত্যুর পর দেহের কোষগুলোও মারা যায়। মাটির নিচে বহু বছর ধরে এইভাবে জীবদেহ যখন প্রচন্ড চাপ ও তাপের সম্মুখীন হতে থাকে। তখন জীবদেহের প্রত্যেকটি কোষের মধ্যে যে প্রোটোপ্লাজম রয়েছে, তাকে হটিয়ে দিয়ে তার জায়গা দখল করে বসে নানা রকম খনিজ পদার্খ এবং তা কঠিন পদার্থ পাথর বা ফসিলে পরিণত হয়।
Satabdi Das https://othervoice.in/article/ov-7-6-22-4-silicosis

* Garbage

+ Areej Fatima
+ Kish Sharma
+ Asmee (2021)
+ Everything Everywhere All at Once 2022 ‧ Sci-fi/Adventure ‧
+ Banana Fish 2018
+ The Dark Side of the Heart (El lado oscuro del corazón) 1992
+ Mehdi Hassan (Pakistani singer)
+ Mansur Al-Hallaj
https://www.canvasmagazine.com.bd/2018/09/07/8187/
https://www.songbadprokash.com/m/literature-culture/%E0%A6%87%E0%A6%A4%E0%A6%BF%E0%A6%B9%E0%A6%BE%E0%A6%B8%E0%A7%87%E0%A6%B0-%E0%A6%AC%E0%A6%BF%E0%A6%95%E0%A7%83%E0%A6%A4%E0%A6%BF-%E0%A6%87%E0%A6%A4%E0%A6%BF%E0%A6%B9%E0%A6%BE%E0%A6%B8-%E0%A6%A5%E0%A7%87%E0%A6%95%E0%A7%87/28674
https://www.bdsexeducation.com/
https://www.shongshoy.com/%E0%A6%87%E0%A6%AC%E0%A6%A8%E0%A7%87-%E0%A6%B8%E0%A6%BF%E0%A6%A8%E0%A6%BE-%E0%A6%95%E0%A7%80-%E0%A6%AE%E0%A7%81%E0%A6%B8%E0%A6%B2%E0%A6%BF%E0%A6%AE-%E0%A6%9B%E0%A6%BF%E0%A6%B2%E0%A7%87%E0%A6%A8/

* সব ভিগানই নিরামিষাশী, কিন্তু সব নিরামিষাশী ভিগান নন
** ভিগান এ ভেজিটারিয়ান এর মধ্যে পার্থক্য কী?

ভেজিটারিয়ানিজম বা নিরামিষভোজন মতবাদটির উৎপত্তি ঘটেছিল সাধারণত ধর্মীয় বা আধ্যাত্মিক
কারণে। হিন্দু ধর্ম ও জৈন ধর্মের মতো কিছু ধর্মই নিরামিষবাদ নির্ধারণ করে বা উত্সাহ দেয়।
অন্যরা, কিছু খ্রিস্টান সম্প্রদায়ের মতো, লেন্টের সময় প্রাণীজাতীয় পণ্য থেকে বিরত থাকার
অনুশীলন করে। মূলত এই ধারণা-- প্রাণীর প্রতি অহিংস মতবাদের সঙ্গে সম্পর্কিত, ভারতে অহিংসা
নামে পরিচিত। যার মূল কথা হচ্ছে-- প্রাণীহত্যা থেকে বিরত থাকা। যেহেতু নিরামিষভোজন
মতবাদটি ধর্মের হাত ধরেই এসেছে, তাই এ মতবাদের সাথে ধর্মের কিছু মিথ চলে আসে, যার
কারণে কিছু উদ্ভিদ জাতীয় খাদ্য(পেঁয়াজ-রসুন, মুসর ডাল) এ খাদ্যাভাস থেকে বাদ পড়ে যায়। তাই
নিরামিষভোজিরা কোনো প্রকার মাছ, ডিম, প্রাণীর মাংস(সামুদ্রিক প্রাণীসহ), পেঁয়াজ-রসুন, মুসর
ডাল খদ্যগ্রহণ করা থেকে বিরত থাকেন। কিন্তু তারা সরাসরি প্রণী হত্যার সাথে জড়িত না থাকলেও
তাদের গৃহীত অনেক খাদ্য, ব্যবহৃত অনেক বস্ত্র কোনো না কোনোভাবে প্রাণীদের হত্যা বা
নির্যাতনের মাধ্যমেই আসে। যেমন দুধ ও দুগ্ধজাত দ্রব্য, মধু, বিভিন্ন প্রাণিজ দ্রব্য এমনকি প্রাণী
জাতীয় পণ্য :- চামড়ার তৈরি জুতা অথবা জামাকাপড় প্রভৃতি যা তারা সচরাচর ব্যবহার করেন।
কিন্তু এ নিয়ে তাদের কোনো সমস্যা নেই, তারা নির্ধিদায় এগুলো ব্যবহার করে থাকে। অন্যদিকে
ভিগানরা তাঁদের জীবন থেকে সম্পূর্ণভাবে প্রাণিজ দ্রব্য ও পণ্য বর্জন করেন। মৌমাছির প্ররিশ্রমে
সংগ্রহ করা মধু, উল, চামড়া বা সিল্কের পোশাক, মুক্তো ব্যবহার করেন না। আর এখানেই
ভেজিটারিয়ান থেকে ভিগান সম্পূর্ণভাবে আলাদা। ভিগান বা ভিগানিজম কেবল একটি ডায়েট কিংবা
খাদ্যাভ্যাস নয়, এর চেয়েও বেশি- এমন একটি দর্শন এবং জীবনধারা যা খাদ্য, পোশাক বা অন্য
কোনও উদ্দেশ্যে প্রাণীর সমস্ত প্রকার শোষণ ও তাড়না বাদ দিতে চায়।

প্রকৃতপক্ষে ভেগানিজম হচ্ছে ভেজিটিরিয়ান শব্দটির একটি অর্থোডক্স সংস্করণ; ‘ভেজিটেরিয়ান’
শব্দের প্রথম এবং শেষ বর্ণগুলি একত্রিত করে তৈরি হয়েছে ‘ভেগান’ (Vegan) শব্দটি। Vegan
দর্শন প্রাণী স্বাধীনতা এবং মুক্তি এবং vegans উপর ভিত্তি করে; মানুষের কেন্দ্রস্থলে একটি
বিশ্বদর্শন এবং ইউটিলিটিভ পদ্ধতির বিরোধিতা করা, একটি সম্পূর্ণ উদ্ভিদ এবং ফল-ভিত্তিক খাদ্য
গ্রহণ করা, কোনও প্রাণী-ভিত্তিক বা প্রাণী-পরীক্ষিত উপকরণ বা পণ্য ব্যবহার না করা এবং
চিড়িয়াখানা, প্রাণী সার্কাস, সামুদ্রিক পার্ক, থিম্যাটিক অ্যাকোয়ারিয়াম, এবং প্রতিরোধের জন্য
এটিকে আপত্তিজনক যে কোনও বিনোদনের অস্বীকার করা মানবেতর মানুষের প্রতি এটি একটি নৈতিক
দায়িত্ব হিসাবে বিবেচিত। "মাংস খাওয়া এবং দুগ্ধজাতীয় প্রাণী বা অন্যান্য প্রাণীজাতীয় খাবার
খাওয়ার মধ্যে কোনও অর্থপূর্ণ পার্থক্য নেই। দুগ্ধ শিল্পে ব্যবহৃত প্রাণীগুলি মাংসের জন্য ব্যবহৃত
সময়ের চেয়ে বেশি সময় বেঁচে থাকে তবে তাদের জীবনকালে তাদের সাথে আরও খারাপ আচরণ করা
হয় এবং তারপরে তারা একই কসাইখানায় পড়ে। আমরা যাইহোক যাইহোক তাদের মাংস গ্রাস করি
probably সম্ভবত একটি গ্লাস দুধ বা আইসক্রিম শঙ্কুতে স্টিকের চেয়ে বেশি যন্ত্রণা রয়েছে "
-গ্যারি এল। ফ্রান্সোইন, ভেজান আমেরিকান আইনী পণ্ডিত এবং প্রাণী অধিকারের উকিল,
ভেগানিজমে: বিলোপবাদী আন্দোলনের মূলনীতি

ভেগানদের মতে, মাছ, মাংস, ডিম, দুধ ও মধু থেকে শুরু করে প্রাণিজ খাবার উৎপাদনে পরিবেশে
প্রচুর পরিমাণে কার্বন ডাই-অক্সাইডসহ বিভিন্ন ধরনের গ্রিনহাউস গ্যাস নিঃসরণ হয়। অন্যদিকে
উদ্ভিদজাত খাদ্য উৎপাদনের ক্ষেত্রে কার্বন ডাই-অক্সাইড কিংবা অন্যান্য গ্রিনহাউস গ্যাসের তেমন
একটা নিঃসরণ হয় না। এমনকি কোনো পদ তৈরি করতে যেসব শাকসবজি, তরিতরকারি কিংবা ফলের
ব্যবহার করা হয়, সেগুলো সম্পূর্ণ অরগানিক পদ্ধতিতে চাষাবাদ করা। কোনো ধরনের রাসায়নিক সার
কিংবা কীটনাশক ছাড়াই সেগুলোর চাষ করা হয়।

এ ছাড়া উদ্ভিদজাত খাদ্য উৎপাদনে অধিক পরিমাণে পানির সাশ্রয় সম্ভব হয় বলে তারা বিশ্বাস
করেন। তাই একবিংশ শতাব্দীতে পৃথিবীর বাস্তুসংস্থানের ওপর সৃষ্ট ঋণাত্মক প্রভাব কমাতে তাঁরা
ভেগানিজমের দর্শন বাস্তবায়নের ওপর অধিক গুরুত্বারোপ করেন।

খাদ্য তালিকায় মাংস না থাকাটা নতুন কিছু নয়। আজ থেকে আড়াই হাজারের বেশি (২৫০০) সময় আগে
প্রাচীন ভারতে এই চর্চা ছিল। এ ছাড়া ভূমধ্যসাগরীয় এলাকাতেও এমন প্রচলন ছিল বলে জানা যায়।
কলিন স্পেনসার তার বই 'ভেজিটেরিয়ানিজম: অ্যা হিস্ট্রি' গ্রন্থে ভারতে নিরামিষ আহারের শুরুর
দিকের ঘটনা বলেছেন।

গ্রীক গণিত শাস্ত্রবিদ পিথাগোরাস নিজেও সকল প্রাণীর প্রতি মমত্ব ও দয়া প্রদর্শনের পক্ষে
বলেছেন। পিথাগোরাস ছিলেন প্রাচীন গ্রিক নাগরিক। খ্রিস্টের জন্মের ৫শ' বছর আগে তিনি জীবিত
ছিলেন। সত্যি বলতে কি, 'ভেজিটেরিয়ান' ধারা জনপ্রিয় হয়ে উঠার আগে 'পিথাগোরিয়ান ডায়েট'
অর্থাৎ যারা খাদ্য তালিকায় মাংস পরিহার করতে তাদেরই বলা হতো পিথাগোরিয়ান ডায়েট মেনে
চলা মানুষ। গবেষণায় আরো দেখা গেছে, মাংসের যোগান বাড়াতে খামারে যে ব্যাপক সংখ্যক
গবাদি-পশু পালন হয় এতে করে প্রচুর মিথেন গ্যাস উৎপন্ন হয়। আর এই গ্যাস জলবায়ুর উষ্ণায়নের
জন্য দায়ী।

যারা ভেগান বা ভেগানিজম চর্চা করে থাকেন, তাদের মধ্যে কয়েকটি ভাগ ও প্রকার রয়েছে। প্রথমত ‘এথিক্যাল ভেগান’, এরা কোনো প্রয়োজনে প্রাণিজ পণ্য গ্রহণ এবং প্রাণীদের বাণিজ্যিক ব্যবহার বর্জন করে থাকেন। কোনো ধরনের মাংস, ডিম, দুগ্ধজাত অথবা এসব দিয়ে তৈরি কোনো খাবার কিংবা প্রাণিজ উপকরণ বর্জন করেন। দ্বিতীয়ত, ‘ডায়েটারি ভেগান’। খাদ্যতালিকা থেকে তারা প্রাণীদের বাদ দেয়। তৃতীয়ত ‘এনভায়রনমেন্টাল ভেগানিজম’, এর অনুসারীরা প্রাণিজ পণ্য বর্জন করার পাশাপাশি বাণিজ্যিকভাবে পশুপালন ও খামার প্রক্রিয়ার বিরোধিতা করে থাকেন। ভেগানদের আরেকটি পর্যায় হচ্ছে র ভেগান (Raw Vegan)। তাদের খাবার ১১৫ ডিগ্রি ফারেনহাইট অথবা ৪৬ ডিগ্রি তাপমাত্রার উপরে রান্না করা হয় না। র ভেগানরা বিশ্বাস করে, এর চেয়ে বেশি তাপমাত্রায় রান্না করা খাবারে সেই পুষ্টি উপাদান থাকে না, যা মানবদেহের জন্য ক্ষতিকর।
# ────────────────────────────────── The End ─────────────────────────────────

* Comfort Zone

There's nothing wrong in looking for comfort. Looking for discomfort actively seems to me a disorder.

The comfort zone is what you strive to achieve , it is the ultimate accomplishment

I just want to point out that there are no absolute statements when it comes to philosophy.

I firmly believe that people can not think at all, until their basic needs/comforts are fulfilled.

/Refrence:/ Abraham Maslow's Hierarchy of needs.

* বাংলা গনণা

ছোটবেলায় আঙুল গুনে হিসাব করতাম - 'একক, দশক, শতক, সহস্র, অযুত, লক্ষ, নিযুত, কোটি'!

আজ একটি বিষয়ে পড়তে গিয়ে জানতে পারলাম বাংলা ভাষাতে সব মিলিয়ে ১৮টি ঘর রয়েছে। একক,
দশক, শতক, সহস্র, অযুত, লক্ষ, নিযুত, কোটি, অর্বুদ, পদ্ম, খর্ব, নিখর্ব, মহাপদ্ম, শঙ্কু, জলধি,
অন্ত্য, মধ্য, পরার্ধ। প্রতিটি ঘর আগের ঘরের মানের দশগুণ। শেখার কোনো শেষ নেই।

@Aniket Mitra
