#+TITLE:  Selective Quotes from Books, Movies & Series
#+AUTHOR: Likhon Barai
#+EMAIL:  likhonhere007@gmail.com
#+DATE:   2022 Nov 15
#+TAGS:   blog

* Table of Contents                                                     :TOC:
- [[#anime][Anime]]
  - [[#jujutsu][Jujutsu]]
- [[#indian][Indian]]
  - [[#gar-gi-2022][Gar gi (2022)]]
- [[#books][Books]]
  - [[#manga][Manga]]
- [[#persons][Persons]]
  - [[#jrr-tolkien][J.R.R. Tolkien]]
  - [[#richard-p-feynman][Richard P. Feynman]]
  - [[#random][Random]]
- [[#bangla][Bangla]]

* Anime
** Jujutsu
- Criminals can only be judge under the law.

* Indian
** Gar gi (2022)

#+begin_quote
At the tip of a teardrop one can glimpse a silver of hope.
#+end_quote

* Books
** Manga
*** 20th Century Boys
By *Naoki Urasawa*

#+begin_quote
People that can't understand this feeling will never understand.
Not that I care whether or not they do.
#+end_quote

#+begin_quote
To have *Strength,* one must know *Weakness*.
And *Weakness,* is *Timidity*.
Timidity* is to wait for *something important*.
To wait for *something important,* is *Strength*.
#+end_quote

#+begin_quote
Open your eyes Ant child..
Open your eyes and look into your fears.
With your eyes shut behind your eyelids, the fear grows larger than it is.
Open your eyes and see through your fear.
Don't avert your eyes from your fears.
#+end_quote

#+begin_quote
How can you be fine...?!
Because my heart stands right here.
Yes, neither Heaven nor Hell... Here.
#+end_quote

#+begin_quote
There's nothing scarier than a military without a leader.
#+end_quote

#+begin_quote
The unreal is more powerful than the real.
Because nothing is as perfect as you can imagine it.
Because it's only intangible ideas, concepts, beliefs, fantasizes that last. Stone crumbles. Wood rots. People, well... They die.
#+end_quote

*** The Fable
By *Katsuhisa Minami*.

Cooking is all about experimental freedom! Just like drawing and music! you make it you'd like to make it.

There's a saying, "It's difficult to live, but troublesome to die."

Just like yesterday, today has arrived. Just like today, tomorrow will come.

Some rich guy who wasn't interested in wearing in a Rolex but preferred wearing a replica. His peers thought was a watch worth a million dollar. And in contrary, young and poor people would work their ass off. Takes on loans and once they bought the original. People would think it a fake.

Those who have no power always end up being hypocrites.

It's The strong guys who win in the end!

You know what they say about capable hawks.. They hide their claws well.

The historian Trevelyan once said, "Education has produced a vast population able to read but unable to distinguish what is worth reading."

Murphy's law - 'You find what you're looking for, when you stop seeking it...'

"A calm thought isn't necessarily the right one."

"Choosing your own death is the one and only proof of a man's freedom."

Human just believe whatever bullshit general theory that gets printed in the press. Spouting "Suicide and murder is no good." Acting all sanctimonious and harping about how special life is, all the while having a big mac in their hands.

* Persons
** J.R.R. Tolkien
#+begin_quote options
    It’s the job that’s never started that takes longest to finish. \\
    — J.R.R. Tolkien
#+end_quote

** Richard P. Feynman

#+begin_quote
I would rather have questions that can't be answered than answers that can't be questioned.
#+end_quote

#+begin_quote
Precise language is not the problem.  Clear language is the problem.
#+end_quote

** Random

#+begin_quote
Every war is just rich men sending poor men to kill other poor men.
— John Merritt
#+end_quote

#+begin_quote
All is forgiven but nothing forgotten.
— Dark series
#+end_quote

- One Piece animation episode - 1050.
- One Piece Manga chapter - 1056.

* Bangla

#+begin_quote
"দেশ থেকে বড় আর কিছু নেই।" — ছোটবেলা থেকে শিখানো ডাহা মিথ্যা 😴
#+end_quote
