#+TITLE:  Selective Quotes from Books, Movies & Series
#+AUTHOR: Likhon Barai
#+EMAIL:  likhonhere007@gmail.com
#+DATE:   2022 Nov 15
#+TAGS:   blog

* Anime
** Jujutsu
- Criminals can only be judge under the law.

* Indian
** Gar gi (2022)
quotes:
- At the tip of a teardrop one can glimpse a silver of hope.

* Books
** Manga
*** 20th Century Boys
- people that can't understand this feeling will never understand.
  Not that I care whether or not they do.

- To have *Strength,* one must know *Weakness*.
  And *Weakness,* is *Timidity*.
  *Timidity* is to wait for *something important*.
  To wait for *something important,* is *Strength*.

+ Open your eyes Ant child..
  Open your eyes and look into your fears.
  With your eyes shut behind your eyelids, the fear grows larger than it is.
  Open your eyes and see through your fear.
  Don't avert your eyes from your fears.

- How can you be fine...?!
  Because my heart stands right here.
  Yes, neither Heaven nor Hell... Here.

* Persons
** J.R.R. Tolkien
#+begin_quote options
    It’s the job that’s never started that takes longest to finish. \\
    — J.R.R. Tolkien
#+end_quote

** Richard P. Feynman

#+BEGIN_QUOTE
  I would rather have questions that can't be answered than answers that can't be questioned.
#+END_QUOTE

#+begin_quote

I would rather have questions that can't be answered than answers that can't be questioned.

#+end_quote



+ I would rather have questions that can't be answered than answers that can't be questioned.
+ Precise language is not the problem.  Clear language is the problem.

** Random
- Every war is just rich men sending poor men to kill other poor men. --John Merritt

+ All is forgiven but nothing forgotten. -- Dark.

- One Piece animation episode - 1042.
- One Piece Manga chapter - 1056.

* Bangla
"দেশ থেকে বড় আর কিছু নেই।"
- ছোটবেলা থেকে শিখানো ডাহা মিথ্যা 😴
